### ISSUE TITLE
Document findCapitalProjectGeoJsonByManagingCodeCapitalProjectId endpoint

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-zoning-api#341]
Based on [this discussion](https://github.com/NYCPlanning/ae-cp-map/discussions/43) we have decided we need an endpoint that returns a single capital project as a geojson feature. This Issue is for creating the OpenAPI spec for that endpoint.

## Acceptance Criteria

- [x] Document new `findCapitalProjectGeoJsonByManagingCodeCapitalProjectId` endpoint in openapi.yaml file, including necessary schemas. See `findTaxLotGeoJsonByBbl` for example.
- [x] The schema for the `properties` object of the geojson feature should use the existing `CapitalProjectBudgeted` schema. 
- [x] Geometry type should be either `MultiPolygon` or `MultiPoint` depending on the existing geometry for the given project - the [oneOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) keyword may be helpful for that. Will require adding new `MultiPoint` schema.
- [x] `MultiPoint` and `MultiPolygon` schemas should have a top level `id` property

**Comment by TangoYankee** [comment]
@horatiorosa and @TylerMatteo 

> MultiPoint and MultiPolygon schemas should have optional top level id property

Two points on this acceptance criteria.

First, the Geometries like "MultiPoint" and "MultiPolygon" do not contain the "id" parameter. They are limited to the properties of "type" and coordinates. [GeoJson Type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/96c55041cb27017e4647c3f88c25bac54a7b2a5d/types/geojson/index.d.ts#L85) and our [MultiPolygon](https://github.com/NYCPlanning/ae-zoning-api/blob/3ece7e53c60211342b69bc17ac624e4ee7766f8f/openapi/openapi.yaml#L1090) OAS implementation. The Id Property exists as a top level property of the GeoJSON. [GeoJson Doc of Feature](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/96c55041cb27017e4647c3f88c25bac54a7b2a5d/types/geojson/index.d.ts#L141) our [TaxLotGeoJson example](https://github.com/NYCPlanning/ae-zoning-api/blob/3ece7e53c60211342b69bc17ac624e4ee7766f8f/openapi/openapi.yaml#L998)

Second, I think it would help with quality of dev life if we were more strict than the GeoJson spec and made the "Id" property "required" in our responses. We can make this promise because we're controlling the API supplying the ID. This should alleviate the number of "undefined" checks we need to do on the frontend to consume the ID.
