### ISSUE TITLE
Implement findCapitalProjectGeoJsonByManagingCodeCapitalProjectId endpoint

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-zoning-api#342]
## Acceptance Criteria

- [x] Implement `findCapitalProjectGeoJsonByManagingCodeCapitalProjectId` as per the OAS spec defined in #341, add tests.
- [x] Top-level geojson feature `id` should be equal the managing code and project id concatenated together into one string, similar to the [managingCodeCapitalProjectId](https://github.com/NYCPlanning/ae-zoning-api/blob/main/src/capital-project/capital-project.repository.ts#L86) property created for the tiles.
- [x] As outlined in the OAS spec, geometry type should be either `MultiPolygon` or `MultiPoint`, depending on the geometry for the given capital project.

## Blocked by
* #341

**Comment by TangoYankee** [comment]
@TylerMatteo and @horatiorosa 

GeoJson coordinates are in "WGS84". However, the capital-project table only stores "Long Island State Plane" and "Web mercator" coordinates. We have two options to obtain the coordinates in "WGS84".

The first option is to convert from "Long Island State Plane" on each request for geojson. This is the simplest implementation because it requires no updates to the database structure or the supporting ETL (data-flow). It also saves on storage because it avoids an additional two columns of data (One for MultiPolygons and another for MultiPoints). It does require more computation because the geometries must be converted between coordinate systems on each request. Though, this should be a fairly lightweight computation.

The second option is to add columns for MultiPoints and MultiPolygons. This requires updating both the database schema to hold the data and the ETL to populate the data. The benefit is that we do the transformations once in the ETL and do not need to do them again on the requests.
