### ISSUE TITLE
Implement Zod schemas based on OpenAPI document

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-zoning-api#73]
# Description
From discussion #55, we need to validate route parameters. We want to base this validation on the route params detailed in the `openapi.yaml` file. We are going to use [Kubb](https://www.kubb.dev) to generate types and zod schemas based on the openapi spec file. This initial ticket is to create the schemas used for validation, and to implement the `400` validation response for one endpoint. It will be followed by other tickets to actually implement the validation for other endpoints. 

## Acceptance criteria
- [ ] Install and configure necessary Kubb packages to generate typescript types and Zod schemas based on OpenAPI spec document.
- [ ] Generate types and schema code with Kubb
- [ ] Implement custom Nest validation pipe that uses Zod for validation based on [Nest example](https://docs.nestjs.com/pipes#object-schema-validation)
- [ ] Implement route param validation for the `/tax-lots/<bbl>` endpoint to serve as reference code for other endpoints

**Comment by TylerMatteo** [comment]
@TangoYankee Overall, this looks good but I have some thoughts/suggestions:

* It's clear from the `drizzle-zod` docs that building schemas meant to validate _api requests and responses_ by refining and subsetting (like with `.pick`) is an intended use case here. I was a little concerned about this at first because you don't necessarily want to just have your API schemas be 1 to 1 with your database schemas, but I see what they're going for here and it makes sense to me.
* This is maybe just semantics but I don't think the [line in your example](https://github.com/NYCPlanning/ae-zoning-api/blob/04a940e73a633127fb15bf2df1e4c7147ad4c3c7/src/schema/tax-lot.ts#L32) where you're making that taxLot schema is quite how `drizzle-zod` wants you to use it. Based on their example, I think the base "select schema" is meant to represent the schema for that data that _is returned by a select statement_, not the schema of API request parameters.
* Have you given any thought as to how this fits in with Nest's overall [request validation strategy](https://docs.nestjs.com/techniques/validation#overview)? Their built in validator uses the `class-validator` and `class-transformer` libraries. I'm more than happy to have us use Zod instead of those, but I think our route-level validation should still make use of Nest's "Pipes" API.

**Comment by TangoYankee** [comment]
> Have you given any thought as to how this fits in with Nest's overall [request validation strategy](https://docs.nestjs.com/techniques/validation#overview)?

TIL about Nest's validation strategy

**Comment by TylerMatteo** [comment]
I think we're mixing terminology a little bit but basically. In my experience, the term _DTO_ is reserved for objects being sent over the network to create or update data, so a simple GET request to `/tax-lots/<bbl>` wouldn't have a DTO, so much as just a schema somewhere in the backend code that defines validation the route params (in this case, just bbl).

In contrast, imagine we implemented an endpoint for the PUT or Patch method to `/tax-lots/<bbl>` that expected the same route param but also a request `body` that was an object of properties to update on the the tax lot with the given bbl. In that scenario, I think you would refer the response body as an instance of the DTO, but the route param isn't part of any DTO.

**Comment by TylerMatteo** [comment]
Turns out Nest shows an [example](https://docs.nestjs.com/pipes#object-schema-validation) of how to create a validation pipe using Zod. Additionally, Kubb (the code-gen library I used on the frontend) includes a [plugin](https://www.kubb.dev/plugins/swagger-zod) for generating Zod schemas based on the OpenAPI yaml file. It might be interesting to look into that for validating route params, query params, and request bodies.

**Comment by TangoYankee** [comment]
It seems there is still necessary discussion around how to generate schemas and validate routes. It would likely be good to capture the summarized thoughts in [this thread](https://github.com/NYCPlanning/ae-zoning-api/discussions/55#discussioncomment-7662304). But I don't want us to dwell on this for too long; any of the solutions will work. But, until we chose one, a lot of tickets are blocked or need to be adjusted around the decision made here.

**Comment by TylerMatteo** [comment]
I agree about needing more discussion. I'll put more thoughts in that discussion. In the interest of making a good enough decision for now, here are a couple decisions we can plan around:
* We are using Zod for validation (whether the schemas are based on the Drizzle schemas, OAS doc, or something else is still up for discussion)
* We want to implement a Nest pipe to handle the Zod validation. This is important for leaning into Nest's architecture. Also, doing things like validation via a pipe that gets assigned via decorator will keep our controller and service code cleaner.

**Comment by TylerMatteo** [comment]
@TangoYankee Summarizing thoughts here:

## Questions
### 1. Which library do we use for runtime validation?
There have been a few mentioned in this thread (`class-validator`, `yup`, `zod`, etc). We're going with Zod for now. If it turns out not to suite out needs, we can re-evaluate

### 2. What do we base out schemas off of for validating network requests?
I think there are really two potential answers here - either we base it off of the underlying database tables (in practice, this means basing it off of the Drizzle schemas), or we base it off of the OpenAPI yaml file.

Of these options, it's best that we base it on the OpenAPI yaml file. Note that we're specifically talking about validating _network requests_. The OAS yaml file is the "source of truth" for what makes a network request to the API valid or not.

### 3. Where does request validation happen in the context of a Nestjs application
Now that we know what library we're using and what to base the schemas off of, we need to know where this validation code actually happens. Note that this mainly concerns `4xx` error responses. For this, we should make use of Nest's "pipes" API. The pipe can then be implemented via decorators on the Controller methods that encapsulate this code. I'll try implementing a custom pipe that uses Zod based on [this example](https://docs.nestjs.com/pipes#object-schema-validation).

**Comment by TangoYankee** [comment]
> @TangoYankee Given our discussion about basing our route param validation on the OpenAPI schema instead of the Drizzle schemas, I was thinking I could change the scope of this issue accordingly:
> 
>     * Install and configure the Kubb code generator to generate Zod schemas and types for the existing OpenAPI document
> 
>     * Add a Zod validation pipe to the repo
> 
>     * Hookup that pipe to the `/tax-lots/<bbl>` endpoint so that it throws a `400` when the param is invalid
> 
> 
> Thoughts?

Makes sense to me
